name: exzeco
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.24.*
  - scipy=1.11.*
  - pandas=2.0.*
  - geopandas=0.14.*
  - rasterio=1.3.*
  - xarray=2023.8.*
  - rioxarray=0.15.*
  - shapely=2.0.*
  - fiona=1.9.*
  - pyproj=3.6.*
  - matplotlib=3.7.*
  - seaborn=0.12.*
  - plotly=5.17.*
  - folium=0.15.*
  - jupyterlab=4.0.*
  - ipywidgets=8.1.*
  - ipyleaflet=0.17.*
  - tqdm=4.66.*
  - joblib=1.3.*
  - numba=0.58.*
  - scikit-image=0.21.*
  - elevation=1.1.*
  - earthpy=0.9.*
  - contextily=1.4.*
  - rasterstats=0.19.*
  - whitebox=2.3.*
  - openpyxl=3.1.*
  - pip
  - pip:
    - pystac-client>=0.7.0
    - planetary-computer>=1.0.0
    - stackstac>=0.5.0
    - kaleido>=0.2.0
